### ISSUE TITLE
Epic 2 submission client readiness checklist

### ISSUE THREAD

**Issue by lliming** [nih-cfde/submission-workflow#25]
- [x] Submission client installation (either github clone or PIP installer, pref. the latter)
- [x] Submission client works against dev, staging, and prod, with prod as default
- [x] Submission transfers data to CFDE GCS collection
- [x] ACLs on GCS collection are set to allow authorized submitters to upload, and CFDE service account to retrieve
- [x] Action provider generates a catalog in Deriva, and submission registry is updated

**Comment by NickolausDS** [comment]
I would be comfortable checking off all these items, although I've been holding off until the bug #23 is fixed. So far, I haven't been able to reproduce it today, with all datasets submitting successfully without issue. I can wait until we narrow down a cause, or I can go ahead and formally move through the list and close the issue.

**Comment by NickolausDS** [comment]
Is finished, with the exception of having epic2 running on prod (since we haven't done a production deployment yet).

**Comment by DavidMichaelKelly** [comment]
All of these steps have been completed
